import Fastify from 'fastify';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { config } from '../config.js';
import { authMiddleware, buildAdminSessionCookie } from './auth.js';

describe('authMiddleware admin session cookie', () => {
  const originalAuthToken = config.authToken;
  const originalAllowlist = [...config.adminIpAllowlist];

  beforeEach(() => {
    config.authToken = 'tmw@13996825050';
    config.adminIpAllowlist = [];
  });

  afterEach(() => {
    config.authToken = originalAuthToken;
    config.adminIpAllowlist = [...originalAllowlist];
  });

  it('accepts encoded admin session cookies generated by the login endpoint', async () => {
    const app = Fastify();
    app.addHook('onRequest', authMiddleware);
    app.get('/api/protected', async () => ({ success: true }));

    const response = await app.inject({
      method: 'GET',
      url: '/api/protected',
      headers: {
        cookie: buildAdminSessionCookie('tmw@13996825050').split(';')[0],
      },
    });

    expect(response.statusCode).toBe(200);
    expect(response.json()).toEqual({ success: true });
    await app.close();
  });
});
