export type ModelCircuitSchemaDialect = 'sqlite' | 'mysql' | 'postgres';

export interface ModelCircuitSchemaInspector {
  dialect: ModelCircuitSchemaDialect;
  tableExists(table: string): Promise<boolean>;
  execute(sqlText: string): Promise<void>;
}

function normalizeSchemaErrorMessage(error: unknown): string {
  if (typeof error === 'object' && error && 'message' in error) {
    return String((error as { message?: unknown }).message || '');
  }
  return String(error || '');
}

function isExistingSchemaError(error: unknown): boolean {
  const lowered = normalizeSchemaErrorMessage(error).toLowerCase();
  return lowered.includes('already exists')
    || lowered.includes('duplicate key name')
    || lowered.includes('relation') && lowered.includes('already exists');
}

async function executeCompatibilitySql(inspector: ModelCircuitSchemaInspector, sqlText: string): Promise<void> {
  try {
    await inspector.execute(sqlText);
  } catch (error) {
    if (!isExistingSchemaError(error)) {
      throw error;
    }
  }
}

const CREATE_TABLE_SQL: Record<ModelCircuitSchemaDialect, string> = {
  sqlite: `CREATE TABLE IF NOT EXISTS route_model_circuits (
    id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
    channel_id integer NOT NULL,
    model_name text NOT NULL,
    state text NOT NULL DEFAULT 'closed',
    fail_count integer NOT NULL DEFAULT 0,
    opened_at text,
    open_until text,
    last_error_at text,
    last_success_at text,
    probe_in_flight integer NOT NULL DEFAULT false,
    updated_at text DEFAULT (datetime('now')),
    FOREIGN KEY (channel_id) REFERENCES route_channels(id) ON DELETE cascade
  );`,
  mysql: 'CREATE TABLE IF NOT EXISTS `route_model_circuits` (`id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY, `channel_id` INT NOT NULL, `model_name` TEXT NOT NULL, `state` TEXT NOT NULL DEFAULT (\'closed\'), `fail_count` INT NOT NULL DEFAULT 0, `opened_at` DATETIME, `open_until` DATETIME, `last_error_at` DATETIME, `last_success_at` DATETIME, `probe_in_flight` BOOLEAN NOT NULL DEFAULT false, `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (`channel_id`) REFERENCES `route_channels`(`id`) ON DELETE CASCADE)',
  postgres: `CREATE TABLE IF NOT EXISTS "route_model_circuits" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, "channel_id" INTEGER NOT NULL, "model_name" TEXT NOT NULL, "state" TEXT NOT NULL DEFAULT 'closed', "fail_count" INTEGER NOT NULL DEFAULT 0, "opened_at" TIMESTAMP, "open_until" TIMESTAMP, "last_error_at" TIMESTAMP, "last_success_at" TIMESTAMP, "probe_in_flight" BOOLEAN NOT NULL DEFAULT false, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("channel_id") REFERENCES "route_channels"("id") ON DELETE CASCADE)`,
};

const CREATE_INDEX_SQL: Record<ModelCircuitSchemaDialect, string[]> = {
  sqlite: [
    'CREATE UNIQUE INDEX IF NOT EXISTS route_model_circuits_channel_model_unique ON route_model_circuits(channel_id, model_name);',
    'CREATE INDEX IF NOT EXISTS route_model_circuits_open_until_idx ON route_model_circuits(open_until);',
    'CREATE INDEX IF NOT EXISTS route_model_circuits_state_idx ON route_model_circuits(state);',
  ],
  mysql: [
    'CREATE UNIQUE INDEX `route_model_circuits_channel_model_unique` ON `route_model_circuits` (`channel_id`, `model_name`(191))',
    'CREATE INDEX `route_model_circuits_open_until_idx` ON `route_model_circuits` (`open_until`)',
    'CREATE INDEX `route_model_circuits_state_idx` ON `route_model_circuits` (`state`(191))',
  ],
  postgres: [
    'CREATE UNIQUE INDEX IF NOT EXISTS "route_model_circuits_channel_model_unique" ON "route_model_circuits" ("channel_id", "model_name")',
    'CREATE INDEX IF NOT EXISTS "route_model_circuits_open_until_idx" ON "route_model_circuits" ("open_until")',
    'CREATE INDEX IF NOT EXISTS "route_model_circuits_state_idx" ON "route_model_circuits" ("state")',
  ],
};

export async function ensureModelCircuitSchemaCompatibility(inspector: ModelCircuitSchemaInspector): Promise<void> {
  const hasRouteChannels = await inspector.tableExists('route_channels');
  if (!hasRouteChannels) return;

  await executeCompatibilitySql(inspector, CREATE_TABLE_SQL[inspector.dialect]);
  for (const statement of CREATE_INDEX_SQL[inspector.dialect]) {
    await executeCompatibilitySql(inspector, statement);
  }
}
