export type ResponseCacheSchemaDialect = 'sqlite' | 'mysql' | 'postgres';

export interface ResponseCacheSchemaInspector {
  dialect: ResponseCacheSchemaDialect;
  tableExists(table: string): Promise<boolean>;
  execute(sqlText: string): Promise<void>;
}

const CREATE_RESPONSE_CACHE_SQL: Record<ResponseCacheSchemaDialect, string[]> = {
  sqlite: [
    `CREATE TABLE IF NOT EXISTS response_cache (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      cache_key text NOT NULL,
      model text NOT NULL,
      response_body text NOT NULL,
      is_stream integer NOT NULL DEFAULT 0,
      prompt_tokens integer DEFAULT 0,
      completion_tokens integer DEFAULT 0,
      hit_count integer NOT NULL DEFAULT 0,
      created_at text NOT NULL,
      expires_at text NOT NULL
    )`,
    'CREATE UNIQUE INDEX IF NOT EXISTS response_cache_key_idx ON response_cache(cache_key)',
    'CREATE INDEX IF NOT EXISTS response_cache_expires_at_idx ON response_cache(expires_at)',
    'CREATE INDEX IF NOT EXISTS response_cache_model_idx ON response_cache(model)',
  ],
  mysql: [
    `CREATE TABLE IF NOT EXISTS \`response_cache\` (
      \`id\` int AUTO_INCREMENT NOT NULL PRIMARY KEY,
      \`cache_key\` VARCHAR(64) NOT NULL,
      \`model\` TEXT NOT NULL,
      \`response_body\` LONGTEXT NOT NULL,
      \`is_stream\` tinyint(1) NOT NULL DEFAULT 0,
      \`prompt_tokens\` int DEFAULT 0,
      \`completion_tokens\` int DEFAULT 0,
      \`hit_count\` int NOT NULL DEFAULT 0,
      \`created_at\` TEXT NOT NULL,
      \`expires_at\` TEXT NOT NULL
    )`,
    'CREATE UNIQUE INDEX `response_cache_key_idx` ON `response_cache`(`cache_key`)',
    'CREATE INDEX `response_cache_expires_at_idx` ON `response_cache`(`expires_at`)',
    'CREATE INDEX `response_cache_model_idx` ON `response_cache`(`model`)',
  ],
  postgres: [
    `CREATE TABLE IF NOT EXISTS "response_cache" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
      "cache_key" VARCHAR(64) NOT NULL,
      "model" TEXT NOT NULL,
      "response_body" TEXT NOT NULL,
      "is_stream" INTEGER NOT NULL DEFAULT 0,
      "prompt_tokens" INTEGER DEFAULT 0,
      "completion_tokens" INTEGER DEFAULT 0,
      "hit_count" INTEGER NOT NULL DEFAULT 0,
      "created_at" TEXT NOT NULL,
      "expires_at" TEXT NOT NULL
    )`,
    'CREATE UNIQUE INDEX IF NOT EXISTS "response_cache_key_idx" ON "response_cache"("cache_key")',
    'CREATE INDEX IF NOT EXISTS "response_cache_expires_at_idx" ON "response_cache"("expires_at")',
    'CREATE INDEX IF NOT EXISTS "response_cache_model_idx" ON "response_cache"("model")',
  ],
};

export async function ensureResponseCacheSchemaCompatibility(
  inspector: ResponseCacheSchemaInspector,
): Promise<void> {
  const hasTable = await inspector.tableExists('response_cache');
  if (hasTable) return;
  for (const sqlText of CREATE_RESPONSE_CACHE_SQL[inspector.dialect]) {
    await inspector.execute(sqlText);
  }
}
