export type TokenCoverageAutoprovisionSchemaDialect = 'sqlite' | 'mysql' | 'postgres';

export interface TokenCoverageAutoprovisionSchemaInspector {
  dialect: TokenCoverageAutoprovisionSchemaDialect;
  tableExists(table: string): Promise<boolean>;
  columnExists(table: string, column: string): Promise<boolean>;
  execute(sqlText: string): Promise<void>;
}

function isIgnorableExistingIndexError(
  dialect: TokenCoverageAutoprovisionSchemaDialect,
  error: unknown,
): boolean {
  if (dialect !== 'mysql') return false;
  const code = typeof error === 'object' && error && 'code' in error
    ? String((error as { code?: unknown }).code || '')
    : '';
  const message = error instanceof Error
    ? error.message
    : String(error || '');
  return code === 'ER_DUP_KEYNAME' || message.includes('Duplicate key name');
}

const CREATE_TABLE_SQL: Record<TokenCoverageAutoprovisionSchemaDialect, string> = {
  sqlite: `CREATE TABLE IF NOT EXISTS token_coverage_autoprovision_states (
    id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
    account_id integer NOT NULL REFERENCES accounts(id) ON DELETE cascade,
    site_id integer NOT NULL REFERENCES sites(id) ON DELETE cascade,
    model_name text NOT NULL,
    target_group text NOT NULL DEFAULT 'default',
    status text NOT NULL DEFAULT 'pending',
    reason_code text,
    message text,
    attempt_count integer NOT NULL DEFAULT 0,
    last_attempt_at text,
    last_success_at text,
    cooldown_until text,
    last_created_token_name text,
    last_created_token_group text,
    created_at text NOT NULL DEFAULT (datetime('now')),
    updated_at text NOT NULL DEFAULT (datetime('now'))
  );`,
  mysql: 'CREATE TABLE IF NOT EXISTS `token_coverage_autoprovision_states` (`id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY, `account_id` INT NOT NULL, `site_id` INT NOT NULL, `model_name` TEXT NOT NULL, `target_group` VARCHAR(191) NOT NULL DEFAULT \'default\', `status` VARCHAR(191) NOT NULL DEFAULT \'pending\', `reason_code` TEXT, `message` TEXT, `attempt_count` INT NOT NULL DEFAULT 0, `last_attempt_at` VARCHAR(191), `last_success_at` VARCHAR(191), `cooldown_until` VARCHAR(191), `last_created_token_name` TEXT, `last_created_token_group` TEXT, `created_at` VARCHAR(191) NOT NULL DEFAULT (DATE_FORMAT(NOW(), \'%Y-%m-%d %H:%i:%s\')), `updated_at` VARCHAR(191) NOT NULL DEFAULT (DATE_FORMAT(NOW(), \'%Y-%m-%d %H:%i:%s\')), CONSTRAINT `token_coverage_autoprovision_states_account_fk` FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON DELETE CASCADE, CONSTRAINT `token_coverage_autoprovision_states_site_fk` FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON DELETE CASCADE)',
  postgres: `CREATE TABLE IF NOT EXISTS "token_coverage_autoprovision_states" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "account_id" INTEGER NOT NULL REFERENCES "accounts"("id") ON DELETE CASCADE, "site_id" INTEGER NOT NULL REFERENCES "sites"("id") ON DELETE CASCADE, "model_name" TEXT NOT NULL, "target_group" TEXT NOT NULL DEFAULT 'default', "status" TEXT NOT NULL DEFAULT 'pending', "reason_code" TEXT, "message" TEXT, "attempt_count" INTEGER NOT NULL DEFAULT 0, "last_attempt_at" TEXT, "last_success_at" TEXT, "cooldown_until" TEXT, "last_created_token_name" TEXT, "last_created_token_group" TEXT, "created_at" TEXT NOT NULL DEFAULT to_char(timezone('UTC', CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS'), "updated_at" TEXT NOT NULL DEFAULT to_char(timezone('UTC', CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS'));`,
};

const CREATE_INDEX_SQL: Record<TokenCoverageAutoprovisionSchemaDialect, string[]> = {
  sqlite: [
    'CREATE UNIQUE INDEX IF NOT EXISTS token_coverage_autoprovision_states_account_model_group_unique ON token_coverage_autoprovision_states(account_id, model_name, target_group);',
    'CREATE INDEX IF NOT EXISTS token_coverage_autoprovision_states_status_cooldown_idx ON token_coverage_autoprovision_states(status, cooldown_until);',
    'CREATE INDEX IF NOT EXISTS token_coverage_autoprovision_states_site_account_idx ON token_coverage_autoprovision_states(site_id, account_id);',
  ],
  mysql: [
    'CREATE UNIQUE INDEX `token_coverage_autoprovision_states_account_model_group_unique` ON `token_coverage_autoprovision_states` (`account_id`, `model_name`(191), `target_group`(191))',
    'CREATE INDEX `token_coverage_autoprovision_states_status_cooldown_idx` ON `token_coverage_autoprovision_states` (`status`(191), `cooldown_until`)',
    'CREATE INDEX `token_coverage_autoprovision_states_site_account_idx` ON `token_coverage_autoprovision_states` (`site_id`, `account_id`)',
  ],
  postgres: [
    'CREATE UNIQUE INDEX IF NOT EXISTS "token_coverage_autoprovision_states_account_model_group_unique" ON "token_coverage_autoprovision_states" ("account_id", "model_name", "target_group");',
    'CREATE INDEX IF NOT EXISTS "token_coverage_autoprovision_states_status_cooldown_idx" ON "token_coverage_autoprovision_states" ("status", "cooldown_until");',
    'CREATE INDEX IF NOT EXISTS "token_coverage_autoprovision_states_site_account_idx" ON "token_coverage_autoprovision_states" ("site_id", "account_id");',
  ],
};

export async function ensureTokenCoverageAutoprovisionSchemaCompatibility(
  inspector: TokenCoverageAutoprovisionSchemaInspector,
): Promise<void> {
  const exists = await inspector.tableExists('token_coverage_autoprovision_states');
  if (!exists) {
    await inspector.execute(CREATE_TABLE_SQL[inspector.dialect]);
  }
  for (const sqlText of CREATE_INDEX_SQL[inspector.dialect]) {
    try {
      await inspector.execute(sqlText);
    } catch (error) {
      if (isIgnorableExistingIndexError(inspector.dialect, error)) {
        continue;
      }
      throw error;
    }
  }
}
